optimizer:  # TODO align with yolox official
  optimizer: momentum
  momentum: 0.9  # SGD momentum/Adam beta1
  nesterov: True # update gradients with NAG(Nesterov Accelerated Gradient) algorithm
  loss_scale: 1.0 # loss scale for optimizer
  group_param: filter_bias_and_bn # group param strategy
  gp_weight_decay: 0.0005  # group param weight decay 5e-4

img_size: [640, 640]

loss:
   name: YOLOxLoss
   input_size: [640, 640]

#
#ms_mode: 1
#ms_jit: False

conf_thres: 0.001  # FIXME align with yolox official 0.01
iou_thres: 0.65


data:
  num_parallel_workers: 8

  train_transforms:
    - {func_name: mosaic, prob: 1.0, mosaic9_prob: 0.0, translate: 0.1, scale: 0.9, degrees: 10.0, shear: 2.0}
    - {func_name: mixup, prob: 1.0, alpha: 8.0, beta: 8.0, needed_mosaic: True } # TODO chage to yolox mixup
    - {func_name: hsv_augment, prob: 1.0, hgain: 0.015, sgain: 0.7, vgain: 0.4} # TODO change to yolox hsv
    - {func_name: label_norm, xyxy2xywh_: True}
    - {func_name: fliplr, prob: 0.5}
    - {func_name: label_pad, padding_size: 160, padding_value: -1}
    - {func_name: image_norm, scale: 255.}
    - {func_name: image_transpose, bgr2rgb: True, hwc2chw: True}

  test_transforms:
    - {func_name: letterbox, scaleup: False}
    - {func_name: label_norm, xyxy2xywh_: True}
    - {func_name: label_pad, padding_size: 160, padding_value: -1}
    - {func_name: image_norm, scale: 255. } # TODO megvii代码没有加这个norm
    - {func_name: image_transpose, bgr2rgb: True, hwc2chw: True }

