__BASE__: [
  '../coco.yaml',
  './hyp.scratch.yaml',
]

weight: /home/zhouwuxing/projects/mindyolo/runs/2023.05.12-09:01:30/weights/yolox-s-285_1848.ckpt
ema_weight: /home/zhouwuxing/projects/mindyolo/runs/2023.05.12-09:01:30/weights/EMA_yolox-s-285_1848.ckpt

optimizer:
  checkpoint_path: /home/zhouwuxing/projects/mindyolo/runs/2023.05.12-09:01:30/weights/optim_yolox-s.ckpt
  lr_init: 0.0005  # fix learning rate of the 2nd part of training, equals to 1st lr_init * end_factor 0.01*0.05

epochs: 15

loss:
   use_l1: True

data:

  train_transforms:
    - {func_name: letterbox, scaleup: False}
    - {func_name: hsv_augment, prob: 1.0, hgain: 0.015, sgain: 0.7, vgain: 0.4} # TODO change to yolox hsv
    - {func_name: label_norm, xyxy2xywh_: True}
    - {func_name: fliplr, prob: 0.5}
    - {func_name: label_pad, padding_size: 160, padding_value: -1}
    - {func_name: image_norm, scale: 255.}
    - {func_name: image_transpose, bgr2rgb: True, hwc2chw: True}


# below are the same as yolox-s.yaml
network:
  model_name: yolox

  depth_multiple: 0.33
  width_multiple: 0.50
  stride: [8, 16, 32]

  depth_wise: False

  backbone:
    # [from, number, module, args]
    [
      [-1, 1, Focus, [64, 3]],                          # 0, stem, /2
      [-1, 1, ConvNormAct, [128, 3, 2]],                # 1, dark2.0, /4
      [-1, 3, C3, [128]],                               # 2, dark2.1, /4
      [-1, 1, ConvNormAct, [256, 3, 2]],                # 3, dark3.0, /8
      [-1, 9, C3, [256]],                               # 4, dark3.1, /8
      [-1, 1, ConvNormAct, [512, 3, 2]],                # 5, dark4.0, /16
      [-1, 9, C3, [512]],                               # 6, dark4.1, /16
      [-1, 1, ConvNormAct, [1024, 3, 2]],               # 7, dark5.0, /32
      [-1, 1, SPPF, [1024]],                            # 8, dark5.1, /32
      [-1, 3, C3, [1024, False]],                       # 9, dark5.2, /32
    ]

  head:
    [
      [-1, 1, ConvNormAct, [512, 1, 1]],                # 10, lateral_conv, /32
      [-1, 1, Upsample, [None, 2, 'nearest']],          # 11, upsample0, /16
      [[-1, 6], 1, Concat, [1]],                        # 12, concat, /16
      [-1, 3, C3, [512, False]],                        # 13, c3_p4, /16

      [-1, 1, ConvNormAct, [256, 1, 1]],                # 14, reduce_conv1, /16
      [-1, 1, Upsample, [None, 2, 'nearest']],          # 15, upsample1, /8
      [[-1, 4], 1, Concat, [1]],                        # 16, concat, /8
      [-1, 9, C3, [256, False]],                        # 17, c3_p3, /8   (small)

      [-1, 1, ConvNormAct, [256, 3, 2]],                # 18, bu_conv2, /16
      [[-1, 14], 1, Concat, [1]],                       # 19, concat, /16
      [-1, 9, C3, [512, False]],                        # 20, c3_n3, /16  (middle)

      [-1, 1, ConvNormAct, [512, 3, 2]],                # 21, bu_conv1, /32
      [[-1, 10], 1, Concat, [1]],                       # 22, concat, /32
      [-1, 9, C3, [1024, False]],                       # 23, c3_n4, /32

      [[17, 20, 23], 1, YOLOxHead, [nc, stride]],                        # detection head
    ]
