__BASE__: [
  '../coco.yaml',
  './hyp.scratch.yaml',
  './yolox-s-2nd.yaml'
]

weight: /home/zhouwuxing/projects/mindyolo/runs/2023.04.28-17:46:25/weights/yolox-darknet53-285_1848.ckpt
ema_weight: /home/zhouwuxing/projects/mindyolo/runs/2023.04.28-17:46:25/weights/EMA_yolox-darknet53-285_1848.ckpt

optimizer:
  checkpoint_path: /home/zhouwuxing/projects/mindyolo/runs/2023.04.28-17:46:25/weights/optim_yolox-darknet53.ckpt

network:
  depth_multiple: 1.0
  width_multiple: 1.0
  backbone: yolofpn

