__BASE__: [
  '../coco.yaml',
  './hyp.scratch.yaml',
]

optimizer:

  lr_init: 0.01  # initial learning rate (SGD=1E-2, Adam=1E-3)
  lr_scheduler: yolox  # quadratic warmup + cosi[ne decay
  start_factor: 1.0
  end_factor: 0.05

  warmup_epochs: 5  # warmup epochs (fractions ok)
  warmup_momentum: 0.8  # warmup initial momentum
  warmup_bias_lr: 0.1  # warmup initial bias lr
  min_warmup_step: 1000 # minimum warmup step


per_batch_size: 8  # 8 * 8 = 64
img_size: 640
sync_bn: True
ms_amp_level: O0
keep_loss_fp32: True

epochs: 285

network:
  model_name: yolox
  backbone: yolopafpn
  num_classes: 80
  depth_wise: False
  input_size: [640, 640]
  depth: 0.33
  width: 0.50
  stride: [8, 16, 32]
  anchors: []
