__BASE__: [
  '../coco.yaml',
  './hyp.scratch.yaml',
  './yolox-s-2nd.yaml'
]

# difference with 2nd training of s
# 1. img_size is 416
# 2. depthwise is true
# 3. depth and width

weight: /home/zhouwuxing/projects/mindyolo/runs/2023.05.08-05:18:55/weights/yolox-nano-285_1848.ckpt
ema_weight: /home/zhouwuxing/projects/mindyolo/runs/2023.05.08-05:18:55/weights/EMA_yolox-nano-285_1848.ckpt

optimizer:
  checkpoint_path: /home/zhouwuxing/projects/mindyolo/runs/2023.05.08-05:18:55/weights/optim_yolox-nano.ckpt

img_size: 416

loss:
   input_size: [416, 416]

network:
  depth: 0.33
  width: 0.25
  depth_wise: True
  input_size: [416, 416]