__BASE__: [
  '../coco.yaml',
  './hyp.scratch.yaml',
  './yolox-s.yaml'
]

weight: /home/zhouwuxing/projects/mindyolo/runs/2023.04.19-09:03:59/weights/yolox-s-49_1848.ckpt
ema_weight: /home/zhouwuxing/projects/mindyolo/runs/2023.04.19-09:03:59/weights/EMA_yolox-s-49_1848.ckpt

optimizer:
  checkpoint_path: /home/zhouwuxing/projects/mindyolo/runs/2023.04.19-09:03:59/weights/optim_yolox-s.ckpt

epochs: 15

loss:
   use_l1: True

data:

  train_transforms:
    - {func_name: letterbox, scaleup: False}
    - {func_name: hsv_augment, prob: 1.0, hgain: 0.015, sgain: 0.7, vgain: 0.4} # TODO change to yolox hsv
    - {func_name: label_norm, xyxy2xywh_: True}
    - {func_name: fliplr, prob: 0.5}
    - {func_name: label_pad, padding_size: 160, padding_value: -1}
    - {func_name: image_norm, scale: 255.}
    - {func_name: image_transpose, bgr2rgb: True, hwc2chw: True}
