__BASE__: [
  '../coco.yaml',
  './hyp.scratch.yaml',
  './yolox-s.yaml'
]

# difference with s
# 1. backbone
# 2. depth and width

network:
  depth_multiple: 1.0
  width_multiple: 1.0
  backbone: yolofpn


