__BASE__: [
  '../coco.yaml',
  './hyp.scratch.yaml',
  './yolox-s.yaml'
]

# difference with s
# 1. no mixup
# 2. mosaic scale is 0.5 and prob is 0.5
# 3. img_size is 416
# 4. multiscale range (random_size) is (10, 20)
# 5. depth and width

img_size: 416

loss:
   input_size: [416, 416]

network:
  depth_multiple: 0.33
  width_multiple: 0.25
  input_size: [416, 416]

  backbone:
    # [from, number, module, args]
    [
      [ -1, 1, Focus, [ 64, 3 ] ],                            # 0, stem, /2
      [ -1, 1, DWConvNormAct, [ 128, 3, 2 ] ],                # 1, dark2.0, /4
      [ -1, 3, DWC3, [ 128 ] ],                               # 2, dark2.1, /4
      [ -1, 1, DWConvNormAct, [ 256, 3, 2 ] ],                # 3, dark3.0, /8
      [ -1, 9, DWC3, [ 256 ] ],                               # 4, dark3.1, /8
      [ -1, 1, DWConvNormAct, [ 512, 3, 2 ] ],                # 5, dark4.0, /16
      [ -1, 9, DWC3, [ 512 ] ],                               # 6, dark4.1, /16
      [ -1, 1, DWConvNormAct, [ 1024, 3, 2 ] ],               # 7, dark5.0, /32
      [ -1, 1, SPPF, [ 1024 ] ],                              # 8, dark5.1, /32
      [ -1, 3, DWC3, [ 1024, False ] ],                       # 9, dark5.2, /32
    ]

  head:
    [
      [ -1, 1, ConvNormAct, [ 512, 1, 1 ] ],                  # 10, lateral_conv, /32
      [-1, 1, Upsample, [ None, 2, 'nearest' ] ],             # 11, upsample0, /16
      [ [ -1, 6 ], 1, Concat, [ 1 ] ],                        # 12, concat, /16
      [ -1, 3, DWC3, [ 512, False ] ],                        # 13, c3_p4, /16

      [ -1, 1, DConvNormAct, [ 256, 1, 1 ] ],                 # 14, reduce_conv1, /16
      [ -1, 1, Upsample, [ None, 2, 'nearest' ] ],            # 15, upsample1, /8
      [ [ -1, 4 ], 1, Concat, [ 1 ] ],                        # 16, concat, /8
      [ -1, 3, DWC3, [ 256, False ] ],                        # 17, c3_p3, /8   (small)

      [ -1, 1, DWConvNormAct, [ 256, 3, 2 ] ],                # 18, bu_conv2, /16
      [ [ -1, 14 ], 1, Concat, [ 1 ] ],                       # 19, concat, /16
      [ -1, 3, DWC3, [ 512, False ] ],                        # 20, c3_n3, /16  (middle)

      [ -1, 1, DWConvNormAct, [ 512, 3, 2 ] ],                # 21, bu_conv1, /32
      [ [ -1, 10 ], 1, Concat, [ 1 ] ],                       # 22, concat, /32
      [ -1, 3, DWC3, [ 1024, False ] ],                       # 23, c3_n4, /32  (large)

      [ [ 17, 20, 23 ], 1, YOLOxHead, [ nc, stride, depth_wise=True] ],       # 24, detection head
    ]

data:

  train_transforms:
    - {func_name: mosaic, prob: 0.5, mosaic9_prob: 0.0, translate: 0.1, scale: 0.5, degrees: 10.0, shear: 2.0} # TODO scale not exactly the same as yolox
    - {func_name: hsv_augment, prob: 1.0, hgain: 0.015, sgain: 0.7, vgain: 0.4} # TODO change to yolox hsv
    - {func_name: label_norm, xyxy2xywh_: True}
    - {func_name: fliplr, prob: 0.5}
    - {func_name: label_pad, padding_size: 160, padding_value: -1}
    - {func_name: image_norm, scale: 255.}
    - {func_name: image_transpose, bgr2rgb: True, hwc2chw: True}
