__BASE__: [
  '../coco.yaml',
  './hyp.scratch.yaml',
]

per_batch_size: 8  # 8 * 8 = 64
img_size: 640
sync_bn: True
ms_amp_level: O0
keep_loss_fp32: True

network:
  model_name: yolox
  backbone: yolopafpn
  num_classes: 80
  depth_wise: False
  input_size: [640, 640]
  depth: 0.33
  width: 0.50
  stride: [8, 16, 32]
  anchors: []
