__BASE__: [
  '../coco.yaml',
  './hyp.scratch.yaml',
  './yolox-s.yaml'
]
# difference with s
# 1. no mixup
# 2. mosaic scale is 0.5
# 3. img_size is 416
# 4. multiscale range is (10, 20)
# 5. depth and width

img_size: [416, 416]

loss:
   input_size: [416, 416]

network:
  depth: 0.33
  width: 0.375

data:

  train_transforms:
    - {func_name: mosaic, prob: 1.0, mosaic9_prob: 0.0, translate: 0.1, scale: 0.5, degrees: 10.0, shear: 2.0} # TODO scale not exactly the same as yolox
    - {func_name: hsv_augment, prob: 1.0, hgain: 0.015, sgain: 0.7, vgain: 0.4} # TODO change to yolox hsv
    - {func_name: label_norm, xyxy2xywh_: True}
    - {func_name: fliplr, prob: 0.5}
    - {func_name: label_pad, padding_size: 160, padding_value: -1}
    - {func_name: image_norm, scale: 255.}
    - {func_name: image_transpose, bgr2rgb: True, hwc2chw: True}


